# Generated by Django 5.1.7 on 2025-04-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pay_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.IntegerField()),
                ('pay_option', models.CharField(max_length=25)),
                ('min_pay', models.IntegerField()),
            ],
        ),
    ]
