# Generated by Django 5.2 on 2025-04-19 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0002_book_posted_by_book_reviewed_at_reviewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='posted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
