# Generated by Django 5.2 on 2025-05-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0004_book_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
