# Generated by Django 5.2 on 2025-04-14 16:59

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_authintication', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField()),
                ('genre', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LendBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='pages.book')),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='user_authintication.profile')),
                ('lender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='user_authintication.profile')),
            ],
        ),
    ]
