# Generated by Django 5.2 on 2025-04-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Best', 'Best'), ('Better', 'Better')], default='New', max_length=50),
        ),
    ]
