# Generated by Django 5.2 on 2025-04-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Better', 'Used but like new')], default='New', max_length=50),
        ),
    ]
