# Generated by Django 5.2 on 2025-04-24 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_book_owner'),
        ('user_authintication', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendborrow',
            name='borrower',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower', to='user_authintication.profile'),
        ),
    ]
