# Generated by Django 5.2 on 2025-04-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_book_allow_bidding_bid_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=250)),
                ('user_name', models.CharField(max_length=100)),
                ('book_id', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
