# Generated by Django 5.2 on 2025-04-24 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_lendborrow_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendborrow',
            name='lend_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendborrow',
            name='lend_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lendborrow',
            name='lend_status',
            field=models.BooleanField(default=False),
        ),
    ]
