# Generated by Django 5.2 on 2025-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_lendborrow_lend_date_lendborrow_lend_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendborrow',
            name='lend_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
