# Generated by Django 5.2 on 2025-04-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_borrowrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
