# Generated by Django 5.2 on 2025-04-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_borrowrequest_accepted_borrowrequest_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='return_status',
            field=models.BooleanField(default=False),
        ),
    ]
