# Generated by Django 5.2 on 2025-04-24 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_borrowrequest_return_status'),
        ('user_authintication', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_date', models.DateTimeField(auto_now=True)),
                ('donate_status', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donateBook', to='pages.book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donateOwner', to='user_authintication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DonateBookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now=True)),
                ('request_status', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('donateBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donateBookRequest', to='pages.donatebook')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to='user_authintication.profile')),
            ],
        ),
    ]
