# Generated by Django 5.2 on 2025-04-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_donatebook_donatebookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatebookrequest',
            name='request_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
