# Generated by Django 5.2 on 2025-04-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_donatebookrequest_request_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatebookrequest',
            name='request_message',
            field=models.TextField(default=''),
        ),
    ]
