# Generated by Django 5.2 on 2025-04-24 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_donatebookrequest_request_message'),
        ('user_authintication', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatebook',
            name='requestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donateRequestor', to='user_authintication.profile'),
        ),
    ]
