# Generated by Django 5.2 on 2025-04-26 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_donatebook_requestor'),
        ('user_authintication', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedBorrower', to='user_authintication.profile'),
        ),
        migrations.AlterField(
            model_name='lendborrow',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower', to='user_authintication.profile'),
        ),
        migrations.AlterField(
            model_name='lendborrow',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='user_authintication.profile'),
        ),
    ]
