# Generated by Django 5.1.7 on 2025-05-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_wishlistitem'),
        ('pages', '0018_alter_borrowrequest_borrower_and_more'),
    ]

    operations = [
    ]
