# Generated by Django 5.2 on 2025-05-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_merge_20250510_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='allow_bidding',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
