# Generated by Django 5.2 on 2025-05-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_book_allow_bidding_delete_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendborrow',
            name='lend_to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
