# Generated by Django 5.1.7 on 2025-04-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
